[package]
name = "onioncloud-tart-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary.workspace = true
futures-util.workspace = true
libfuzzer-sys.workspace = true
pin-project.workspace = true

[dependencies.tracing]
workspace = true
features = ["max_level_off"]

[dependencies.onioncloud-tart]
path = ".."

[[bin]]
name = "timer"
path = "fuzz_targets/timer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "spsc"
path = "fuzz_targets/spsc.rs"
test = false
doc = false
bench = false

[[bin]]
name = "mpsc"
path = "fuzz_targets/mpsc.rs"
test = false
doc = false
bench = false

[[bin]]
name = "socket"
path = "fuzz_targets/socket.rs"
test = false
doc = false
bench = false
