[package]
name = "onioncloud-tart"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
futures-core.workspace = true
pin-project.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dependencies.futures-util]
workspace = true
features = [
  "io",
]

[dependencies.loom]
workspace = true
optional = true

[dependencies.tracing-subscriber]
workspace = true
features = [
  "env-filter",
]

[dev-dependencies.test-log]
workspace = true
features = [
  "trace",
]

[features]
loom = ["dep:loom"]

[lints.clippy]
undocumented_unsafe_blocks = "deny"
