[package]
name = "onioncloud-ll-relay-cell-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary.workspace = true
libfuzzer-sys.workspace = true

[dependencies.onioncloud-ll-cell]
workspace = true

[dependencies.onioncloud-ll-relay-cell]
workspace = true

[dependencies.tracing]
workspace = true
features = ["max_level_off"]

[dependencies.zerocopy]
workspace = true
features = [
  "derive",
  "std",
]

[[bin]]
name = "cast_cell"
path = "fuzz_targets/cast_cell.rs"
test = false
doc = false
bench = false

[[bin]]
name = "validate_addr"
path = "fuzz_targets/validate_addr.rs"
test = false
doc = false
bench = false
